name: Build

on:
  pull_request:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        required: true
      ANTHROPIC_API_KEY:
        required: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Models should be stored using LFS or downloaded in the pipeline for tests to be run
      # - name: Run tests
      #   run: |
      #     poetry run pytest

      - name: Build
        run: |
          pip install poetry
          poetry build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
